language: python

python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -q Django==1.9
env:
  - DJANGO_VERSION=1.8.2
  - DJANGO_VERSION=1.9
script: coverage run tests/manage.py test
after_success:
  - coveralls

